### ISSUE TITLE
Getting 404 Not Found while uploading plugin

### ISSUE THREAD

**Issue by kashishm** [JetBrains/plugin-repository-rest-client#11]
**command**
```
java -jar ~/Downloads/plugin-repository-rest-client-0.1.15-all.jar upload -host https://plugins.jetbrains.com/ -channel Nightly -username username -password "password" -plugin <number> -file build/distributions/plugin-0.0.1.zip
```

Sometimes, I am getting 404 Not Found with following exception

```
2017-01-09T15:49:44,539 [main] INFO  plugin-repository-rest-client - Uploading plugin <number> from plugin-0.0.1.zip to https://plugins.jetbrains.com/
Exception in thread "main" retrofit.RetrofitError: 404 Not Found
	at retrofit.RetrofitError.httpError(RetrofitError.java:40)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at org.jetbrains.intellij.pluginRepository.$Proxy2.upload(Unknown Source)
	at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.uploadPlugin(pluginRepositoryRest.kt:38)
	at org.jetbrains.intellij.pluginRepository.Uploader$Companion.main(uploader.kt:37)
	at org.jetbrains.intellij.pluginRepository.Uploader.main(uploader.kt)
```

**Comment by WickeDev** [comment]
The problem was resolved when I tried to upload it manually first on website.
