### ISSUE TITLE
CLI failed with RetrofitError: 403

### ISSUE THREAD

**Issue by wisechengyi** [JetBrains/plugin-repository-rest-client#21]
```
$ java -jar scripts/deploy/plugin-repository-rest-client-0.4.27-all.jar upload -host https://plugins.jetbrains.com/ -channel BleedingEdge -username <username> -password <password> -plugin 7412 -file pants_1.8.0.b71853218b5eddff4d8adcf7a8cb4ff0ea905f39.zip
2018-02-28T00:35:43,817 [main] INFO  plugin-repository-rest-client - Uploading plugin 7412 from /Users/yic/workspace/intellij-pants-plugin/pants_1.8.0.b71853218b5eddff4d8adcf7a8cb4ff0ea905f39.zip to https://plugins.jetbrains.com/
Exception in thread "main" retrofit.RetrofitError: 403 
	at retrofit.RetrofitError.httpError(RetrofitError.java:40)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at org.jetbrains.intellij.pluginRepository.$Proxy2.upload(Unknown Source)
	at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.uploadPlugin(pluginRepositoryRest.kt:82)
	at org.jetbrains.intellij.pluginRepository.Client$Companion.upload(client.kt:54)
	at org.jetbrains.intellij.pluginRepository.Client$Companion.main(client.kt:18)
	at org.jetbrains.intellij.pluginRepository.Client.main(client.kt)
```

Our plugin was auto released until `plugin-repository-rest-client` was broken for us since between Jan - Feb 2018 (https://plugins.jetbrains.com/plugin/7412-pants-support -> BleedingEdge channel), so I had to do it manually for https://plugins.jetbrains.com/plugin/7412-pants-support/update/43711

The username and password are correct. Tried with both 
`plugin-repository-rest-client-0.3.SNAPSHOT-all.jar` and
`plugin-repository-rest-client-0.4.27-all.jar`, the error is the same.

**Comment by wisechengyi** [comment]
Any idea @chashnikov @satamas?

**Comment by wisechengyi** [comment]
Resolved with https://youtrack.jetbrains.com/issue/JT-46456
