### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by wisechengyi** [JetBrains/plugin-repository-rest-client#9]
I want to try it out as I also plan to automate the plugin release process, but not having a README makes a little hard. So...can we have one?

**Comment by zolotov** [comment]
@wisechengyi I'm sorry but there is literally [single file](../blob/master/rest/src/main/kotlin/pluginRepositoryRest.kt), I don't think it requires any description.

As for automatization plugin release processes, you may want to look at [gradle intellij plugin](https://github.com/JetBrains/gradle-intellij-plugin).

**Comment by wisechengyi** [comment]
Also is this the correct usage? Got the following error
```
$ java -jar build/libs/plugin-repository-rest-client-0.3.SNAPSHOT-all.jar upload -host https://plugins.jetbrains.com/ -channel BleedingEdge -username $USERNAME -password "$PASSWORD" -plugin 7412 -file plugin.zip
2016-11-30T12:02:44,082 [main] INFO  plugin-repository-rest-client - Uploading plugin 7412 from /Users/yic/workspace/intellij-pants-plugin/dist/intellij-pants-plugin.zip to https://plugins.jetbrains.com/
Exception in thread "main" retrofit.RetrofitError: 500 Internal Server Error
	at retrofit.RetrofitError.httpError(RetrofitError.java:40)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at org.jetbrains.intellij.pluginRepository.$Proxy2.upload(Unknown Source)
	at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.uploadPlugin(pluginRepositoryRest.kt:41)
	at org.jetbrains.intellij.pluginRepository.Client$Companion.upload(client.kt:54)
	at org.jetbrains.intellij.pluginRepository.Client$Companion.main(client.kt:18)
	at org.jetbrains.intellij.pluginRepository.Client.main(client.kt)
```

**Comment by zolotov** [comment]
@wisechengyi yes, it looks like correct usage. I don't know the reason of 500 response. Are you sure that the archive is valid? You can try to upload it via WEB-interface to ensure that it's ok.

**Comment by wisechengyi** [comment]
@zolotov thanks for the confirmation. Yes it does work via the web interface. Will investigate further...

**Comment by wisechengyi** [comment]
ok it was username/password typo. However, the error message can be a little better on the server side.

**Comment by zolotov** [comment]
@wisechengyi thank you for update. I reported an issue to plugin repository's maintainers.
